spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
    username: zzq
    password: zambia520
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # 没有这句会出错
    database-platform: org.hibernate.dialect.MySQL8Dialect